spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/create?seUnicode=true&characterEncoding=utf8&serverTimezone=UTC
  jackson:
    property-naming-strategy: CAMEL_CASE_TO_LOWER_CASE_WITH_UNDERSCORES
  thymeleaf:
    prefix: classpath:/templates/
    servlet:
      content-type: text/html
    mode: LEGACYHTML5
    cache: false
    #指明静态资源(为restful接口风格做准备)
    resources:
      static-locations: classpath:/static